version: '3'
services:
  wms:
    build:
      context: .
      dockerfile: packages/wms/Dockerfile
    image: wms:latest
    container_name: wms
    volumes:
      - ./packages/wms/dist:/usr/share/nginx/html
    networks:
      - frontend
    ports:
      - "8081:80"

  worker:
    build:
      context: .
      dockerfile: packages/worker/Dockerfile
    image: worker:latest
    container_name: worker
    volumes:
      - ./packages/worker/dist:/usr/share/nginx/html
    networks:
      - frontend
    ports:
      - "8082:80"

networks:
  frontend:
    driver: bridge