version: '3.8'

services:
  wms:
    build:
      context: .
      dockerfile: packages/wms/Dockerfile
    image: wms:latest
    container_name: wms
    volumes:
      - ./packages/wms/dist:/usr/share/nginx/html/wms
    networks:
      - frontend
    expose:
      - "8081"  # Nginx에서 사용할 포트

  worker:
    build:
      context: .
      dockerfile: packages/worker/Dockerfile
    image: worker:latest
    container_name: worker
    volumes:
      - ./packages/worker/dist:/usr/share/nginx/html/worker
    networks:
      - frontend
    expose:
      - "8082"  # Nginx에서 사용할 포트

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx 설정 파일 마운트
    ports:
      - "80:80"  # 80번 포트를 외부에 노출
    depends_on:
      - wms
      - worker
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
