version: '3'

services:
  wms:
    build:
      context: .
      dockerfile: packages/wms/Dockerfile
    image: ${DOCKER_TAG_WMS}
    container_name: wms
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./packages/wms/dist:/usr/share/nginx/html
    networks:
      - frontend
    ports:
      - "8081:80"

networks:
  frontend:
    driver: bridge